### ISSUE TITLE
Questions about the code. 

### ISSUE THREAD

**Issue by mcale6** [patrickbryant1/AFProfile#1]
Very important improvement of AF-m!

Are the template features zeroed in the predictions?

What is meant with "sample" in the gif. "Optimisation for 6nnw"? (Are these recycling steps?)

**Comment by patrickbryant1** [comment]
1. Yes, the template features are set to zero.
2. Sample here is gradient descent step. These are not recycling steps.

There is more information here: https://www.biorxiv.org/content/10.1101/2023.07.04.547638v1

Hope this helps!
