### ISSUE TITLE
Error installing AFProfile conda environment

### ISSUE THREAD

**Issue by Franz4272** [patrickbryant1/AFProfile#10]
Hi Patrick,

I hope you are having a nice weekend. We got errors that the AFProfile conda environment cannot be installed anymore due to version conflict of the libraries. Conda could not resolve the conflicts in the prescribed versions of the libraries and stopped. We used the latest version of conda. Please let me know your thoughts when you have time. 

Thank you,
Franz

**Comment by patrickbryant1** [comment]
Hi Franz,

Can you try this after you activate the env:
pip install --upgrade "jax[cuda12_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
pip install --upgrade numpy

I think something changed in the new JAX coda_12 version.

Can you provide the error message you get otherwise?

Patrick

**Comment by Franz4272** [comment]
Hi Patrick,

I followed what you suggested. I attached a screenshot of the error message. Please let me know what you think when you have time. 

Thank you,
Franz 

<img width="1512" alt="error AFProfile 3:3:24" src="https://github.com/patrickbryant1/AFProfile/assets/100600329/64c04813-03f1-41fd-8dd7-bc69919c9033">

**Comment by patrickbryant1** [comment]
Hi Franz,

Also do:
conda install dm-haiku

**Comment by Franz4272** [comment]
Hi Patrick,

I hope you're having a nice weekend so far. I followed your suggestion, but I got another error. I'm not sure what you would recommend. I attached a screenshot of the error. We followed the installation instructions, so hmmer should be installed. 

Thank you,
Franz 

<img width="1512" alt="error AFProfile 3:5:24" src="https://github.com/patrickbryant1/AFProfile/assets/100600329/6fff9f9b-9161-4f2c-8c8d-00439d7ed0e4">

**Comment by patrickbryant1** [comment]
Hi Franz,

It seems that the pdb_seqres database is not found. It looks like you downloaded it into a temporary directory? 

Please make sure that all databases are there and then I think it should work.

Best,

Patrick

**Comment by Franz4272** [comment]
Hi Patrick,

We double-checked the pdb_seqres database and AFProfile unfortunately still can't run with the new jax on A40 or A100. I noticed on the A40 there was a FutureWarning "/opt/conda/lib/python3.8/site-packages/jax/_src/ops/scatter.py:87: FutureWarning: scatter inputs have incompatible types: cannot safely cast value from type=float32 to type=bfloat16. In future JAX releases this w ill result in an error." I'll keep thinking about what else to try. 

Best,
Franz

**Comment by patrickbryant1** [comment]
Hi,

Please ensure these are not in a tmpdir. I think the current installation should work with cuda12 (it works for me on many different clusters/locally). Can you try to remove the conda env and reinstall it and run the test case? Then provide any error messages here and I can have a look.

Best,

Patrick

**Comment by harshagrawal13** [comment]
Is it possible @patrickbryant1 that you can add a simpler `env.yaml` file? The one you've mentioned is too stringent and is failing due to very strict dependency issues. 

Could you kindly run this: `conda env export --from-history -f environment.yml` and post the result?

**Comment by patrickbryant1** [comment]
Hi, we will look into this. An issue is that the package requirements are constantly changing, this is why the exact versions are set.

Best,

Patrick
