### ISSUE TITLE
Can afprofile Utilize Full Databases or Is It Limited to Small BFD Only?

### ISSUE THREAD

**Issue by ryan2han** [patrickbryant1/AFProfile#11]
Hi, Patrick

I'm using afprofile and wondering if it supports full databases, or is it limited to the small BFD only?

Thanks
Ryan

**Comment by patrickbryant1** [comment]
Hi Ryan,

Yes you can. Simply change the flags in the msa feature generation script: https://github.com/patrickbryant1/AFProfile/blob/main/src/generate_msas.sh

Best,

Patrick

**Comment by ryan2han** [comment]
But i got an error when setting full BFD.  
![image](https://github.com/patrickbryant1/AFProfile/assets/61266296/82a418ed-c789-4be7-b8d3-a93c3d230ef5)
![image](https://github.com/patrickbryant1/AFProfile/assets/61266296/c250f54d-0c74-486c-8b6a-d47dd0dc8419)

**Comment by ryan2han** [comment]
I have solved it. Right setting below.

```
# Path and user config (change me if required)
parameter_path="$data_dir/params"
bfd_database_path="$data_dir/bfd/bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt"
small_bfd_database_path="$data_dir/small_bfd/bfd-first_non_consensus_sequences.fasta"
mgnify_database_path="$data_dir/mgnify/mgy_clusters_2022_05.fa"
template_mmcif_dir="$data_dir/pdb_mmcif/mmcif_files"
obsolete_pdbs_path="$data_dir/pdb_mmcif/obsolete.dat"
pdb70_database_path="$data_dir/pdb70/pdb70"
pdb_seqres_database_path="$data_dir/pdb_seqres/pdb_seqres.txt"
uniref30_database_path="$data_dir/uniref30/UniRef30_2021_03"  # We recommend this use the 2020 version of uniclust
uniref90_database_path="$data_dir/uniref90/uniref90.fasta"
uniprot_database_path="$data_dir/uniprot/uniprot.fasta"
```
