### ISSUE TITLE
Memory Requirements

### ISSUE THREAD

**Issue by tkramer-motion** [patrickbryant1/AFProfile#12]
How much GPU memory is required to run the example? I've tried on a GPU with 24GB and am getting OOM errors. What cards have you tested on?

**Comment by patrickbryant1** [comment]
Hi,
We used A100 (40 Gb). The gradient descent increases the memory requirement compared to a single fwd pass.

**Comment by tkramer-motion** [comment]
Thanks

**Comment by tkramer-motion** [comment]
I tried running on an A100 (40 GB) and am still getting OOM errors.

```
The MSA has shape: (512, 532)
2024-07-31 20:57:56.846076: W external/xla/xla/service/hlo_rematerialization.cc:3005] Can't reduce memory use below 12.46GiB (13379584647 bytes) by rematerialization; only reduced to 21.28GiB (22848300023 bytes), down from 21.58GiB (23170454683 bytes) originally
2024-07-31 21:00:06.346837: E external/xla/xla/service/slow_operation_alarm.cc:65] Constant folding an instruction is taking > 1s:

  %pad.12 = f32[256,532,256]{2,1,0} pad(f32[252,532,256]{2,1,0} %broadcast.111, f32[] %constant.104), padding=0_4x0_0x0_0, metadata={op_name="jit(apply_fn)/jit(main)/alphafold/alphafold_iteration/while/body/evoformer/pad[padding_config=((0, 4, 0), (0, 0, 0), (0, 0, 0))]" source_file="/app/AFProfile/src/alphafold/model/modules_multimer.py" source_line=825}

This isn't necessarily a bug; constant-folding is inherently a trade-off between compilation time and speed at runtime. XLA has some guards that attempt to keep constant folding from taking too long, but fundamentally you'll always be able to come up with an input program that takes a long time.

If you'd like to file a bug, run with envvar XLA_FLAGS=--xla_dump_to=/tmp/foo and attach the results.
2024-07-31 21:00:08.079214: E external/xla/xla/service/slow_operation_alarm.cc:133] The operation took 2.732475153s
Constant folding an instruction is taking > 1s:

  %pad.12 = f32[256,532,256]{2,1,0} pad(f32[252,532,256]{2,1,0} %broadcast.111, f32[] %constant.104), padding=0_4x0_0x0_0, metadata={op_name="jit(apply_fn)/jit(main)/alphafold/alphafold_iteration/while/body/evoformer/pad[padding_config=((0, 4, 0), (0, 0, 0), (0, 0, 0))]" source_file="/app/AFProfile/src/alphafold/model/modules_multimer.py" source_line=825}

This isn't necessarily a bug; constant-folding is inherently a trade-off between compilation time and speed at runtime. XLA has some guards that attempt to keep constant folding from taking too long, but fundamentally you'll always be able to come up with an input program that takes a long time.

If you'd like to file a bug, run with envvar XLA_FLAGS=--xla_dump_to=/tmp/foo and attach the results.
2024-07-31 21:00:15.558837: W external/xla/xla/service/hlo_rematerialization.cc:3005] Can't reduce memory use below 15.35GiB (16485016272 bytes) by rematerialization; only reduced to 20.40GiB (21906597664 bytes), down from 23.07GiB (24772675528 bytes) originally
2024-07-31 21:00:36.134920: W external/xla/xla/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_0_bfc) ran out of memory trying to allocate 18.68GiB (rounded to 20059973376)requested by op 
2024-07-31 21:00:36.136358: W external/xla/xla/tsl/framework/bfc_allocator.cc:494] ***********************************************************_________________________________________
E0731 21:00:36.136449    2932 pjrt_stream_executor_client.cc:3067] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 20059973160 bytes.
Traceback (most recent call last):
  File "/app/AFProfile/src/.//run_AFP.py", line 340, in <module>
    app.run(main)
  File "/opt/conda/lib/python3.11/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/opt/conda/lib/python3.11/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/app/AFProfile/src/.//run_AFP.py", line 319, in main
    predict_structure(
  File "/app/AFProfile/src/.//run_AFP.py", line 250, in predict_structure
    loss, aux, msa_params, opt_state = update(msa_params, opt_state, processed_feature_dict)
  File "/app/AFProfile/src/.//run_AFP.py", line 231, in update
    (loss, aux), grads = jax.value_and_grad(loss_fn, has_aux=True)(msa_params, processed_feature_dict)
  File "/app/AFProfile/src/.//run_AFP.py", line 223, in loss_fn
    prediction_result = model_runner.predict(msa_params, processed_feature_dict) #The params for model runner are contained within self
  File "/app/AFProfile/src/alphafold/model/model.py", line 170, in predict
    result = self.apply(self.params, jax.random.PRNGKey(0), feat)
jax._src.source_info_util.JaxStackTraceBeforeTransformation: jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 20059973160 bytes.

The preceding stack trace is the source of the JAX operation that, once transformed by JAX, triggered the following exception.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/AFProfile/src/.//run_AFP.py", line 340, in <module>
    app.run(main)
  File "/opt/conda/lib/python3.11/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/opt/conda/lib/python3.11/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "/app/AFProfile/src/.//run_AFP.py", line 319, in main
    predict_structure(
  File "/app/AFProfile/src/.//run_AFP.py", line 250, in predict_structure
    loss, aux, msa_params, opt_state = update(msa_params, opt_state, processed_feature_dict)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/AFProfile/src/.//run_AFP.py", line 231, in update
    (loss, aux), grads = jax.value_and_grad(loss_fn, has_aux=True)(msa_params, processed_feature_dict)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 20059973160 bytes.
--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
```

**Comment by patrickbryant1** [comment]
I think the first error indicates that something is wrong with your CUDA. Please check that all package versions match. The example provided should fit easily on 40gb.

Best,

Patrick

**Comment by Maryam-Haghani** [comment]
Hello @patrickbryant1 
**I am also run into OOM error while trying to run the code for T1123 using the provided features.pkl file on a GPU with 80GB memory.** Here is the error:

> 0806 14:42:39.435870 23456247948800 run_AFP.py:304] Have 1 models: ['model_1_multimer_v3_pred_0']
> I0806 14:42:39.436035 23456247948800 run_AFP.py:314] Using random seed 5532440738102414944 for the data pipeline
> I0806 14:42:39.436288 23456247948800 run_AFP.py:160] Predicting T1123
> 2024-08-06 14:43:33.378237: W external/xla/xla/service/gpu/ir_emitter_triton.cc:761] Shared memory size limit exceeded.
> 2024-08-06 14:43:33.543451: W external/xla/xla/service/gpu/ir_emitter_triton.cc:761] Shared memory size limit exceeded.
> 2024-08-06 14:43:55.036679: W external/xla/xla/service/hlo_rematerialization.cc:2194] Can't reduce memory use below 59.36GiB (63740805120 bytes) by rematerialization; only reduced to 1.54TiB (1694494131250 bytes)
> 2024-08-06 14:44:44.977818: W external/tsl/tsl/framework/bfc_allocator.cc:485] Allocator (GPU_0_bfc) ran out of memory trying to allocate 103.65GiB (rounded to 111289565184)requested by op 
> 2024-08-06 14:44:44.978224: W external/tsl/tsl/framework/bfc_allocator.cc:497] *___________________________________________________________________________________________________
> The MSA has shape: (512, 532)
> iteration: 1
> []
> Traceback (most recent call last):
>   File "./run_AFP.py", line 342, in <module>
>     app.run(main)
>   File "/home/haghani/.conda/envs/afprofile/lib/python3.8/site-packages/absl/app.py", line 312, in run
>     _run_main(main, args)
>   File "/home/haghani/.conda/envs/afprofile/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
>     sys.exit(main(argv))
>   File "./run_AFP.py", line 321, in main
>     predict_structure(
>   File "./run_AFP.py", line 252, in predict_structure
>     loss, aux, msa_params, opt_state = update(msa_params, opt_state, processed_feature_dict)
>   File "./run_AFP.py", line 231, in update
>     (loss, aux), grads = jax.value_and_grad(loss_fn, has_aux=True)(msa_params, processed_feature_dict)
>   File "/home/haghani/.conda/envs/afprofile/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
>     return fun(*args, **kwargs)
>   File "/home/haghani/.conda/envs/afprofile/lib/python3.8/site-packages/jax/_src/api.py", line 738, in value_and_grad_f
>     ans, vjp_py, aux = _vjp(
>   File "/home/haghani/.conda/envs/afprofile/lib/python3.8/site-packages/jax/_src/api.py", line 2284, in _vjp
>     out_primal, out_vjp, aux = ad.vjp(
>   File "/home/haghani/.conda/envs/afprofile/lib/python3.8/site-packages/jax/_src/interpreters/ad.py", line 141, in vjp
>     out_primals, pvals, jaxpr, consts, aux = linearize(traceable, *primals, has_aux=True)
>   File "/home/haghani/.conda/envs/afprofile/lib/python3.8/site-packages/jax/_src/interpreters/ad.py", line 128, in linearize
>     jaxpr, out_pvals, consts = pe.trace_to_jaxpr_nounits(jvpfun_flat, in_pvals)
>   File "/home/haghani/.conda/envs/afprofile/lib/python3.8/site-packages/jax/_src/profiler.py", line 314, in wrapper
>     return func(*args, **kwargs)
>   File "/home/haghani/.conda/envs/afprofile/lib/python3.8/site-packages/jax/interpreters/partial_eval.py", line 771, in trace_to_jaxpr_nounits
>     jaxpr, (out_pvals, consts, env) = fun.call_wrapped(pvals)
>   File "/home/haghani/.conda/envs/afprofile/lib/python3.8/site-packages/jax/_src/linear_util.py", line 166, in call_wrapped
>     ans = self.f(*args, **dict(self.params, **kwargs))
>   File "./run_AFP.py", line 223, in loss_fn
>     prediction_result = model_runner.predict(msa_params, processed_feature_dict) #The params for model runner are contained within self
>   File "/projects/protein-structure-prediction/AFProfile/src/alphafold/model/model.py", line 170, in predict
>     result = self.apply(self.params, jax.random.PRNGKey(0), feat)
>   File "/home/haghani/.conda/envs/afprofile/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
>     return fun(*args, **kwargs)
>   File "/home/haghani/.conda/envs/afprofile/lib/python3.8/site-packages/jax/_src/pjit.py", line 248, in cache_miss
>     outs, out_flat, out_tree, args_flat = _python_pjit_helper(
>   File "/home/haghani/.conda/envs/afprofile/lib/python3.8/site-packages/jax/_src/pjit.py", line 195, in _python_pjit_helper
>     out_flat = pjit_p.bind(*args_flat, **params)
>   File "/home/haghani/.conda/envs/afprofile/lib/python3.8/site-packages/jax/_src/core.py", line 2591, in bind
>     return self.bind_with_trace(top_trace, args, params)
>   File "/home/haghani/.conda/envs/afprofile/lib/python3.8/site-packages/jax/_src/core.py", line 362, in bind_with_trace
>     out = trace.process_primitive(self, map(trace.full_raise, args), params)
>   File "/home/haghani/.conda/envs/afprofile/lib/python3.8/site-packages/jax/_src/interpreters/ad.py", line 315, in process_primitive
>     primal_out, tangent_out = jvp(primals_in, tangents_in, **params)
>   File "/home/haghani/.conda/envs/afprofile/lib/python3.8/site-packages/jax/_src/pjit.py", line 1561, in _pjit_jvp
>     outputs = pjit_p.bind(
>   File "/home/haghani/.conda/envs/afprofile/lib/python3.8/site-packages/jax/_src/core.py", line 2591, in bind
>     return self.bind_with_trace(top_trace, args, params)
>   File "/home/haghani/.conda/envs/afprofile/lib/python3.8/site-packages/jax/_src/core.py", line 362, in bind_with_trace
>     out = trace.process_primitive(self, map(trace.full_raise, args), params)
>   File "/home/haghani/.conda/envs/afprofile/lib/python3.8/site-packages/jax/interpreters/partial_eval.py", line 211, in process_primitive
>     return custom_partial_eval_rules[primitive](self, *tracers, **params)
>   File "/home/haghani/.conda/envs/afprofile/lib/python3.8/site-packages/jax/_src/pjit.py", line 1640, in _pjit_partial_eval
>     all_known_outs = pjit_p.bind(*known_inputs, **known_params)
>   File "/home/haghani/.conda/envs/afprofile/lib/python3.8/site-packages/jax/_src/core.py", line 2591, in bind
>     return self.bind_with_trace(top_trace, args, params)
>   File "/home/haghani/.conda/envs/afprofile/lib/python3.8/site-packages/jax/_src/core.py", line 362, in bind_with_trace
>     out = trace.process_primitive(self, map(trace.full_raise, args), params)
>   File "/home/haghani/.conda/envs/afprofile/lib/python3.8/site-packages/jax/_src/core.py", line 816, in process_primitive
>     return primitive.impl(*tracers, **params)
>   File "/home/haghani/.conda/envs/afprofile/lib/python3.8/site-packages/jax/_src/pjit.py", line 1269, in _pjit_call_impl
>     return compiled.unsafe_call(*args)
>   File "/home/haghani/.conda/envs/afprofile/lib/python3.8/site-packages/jax/_src/profiler.py", line 314, in wrapper
>     return func(*args, **kwargs)
>   File "/home/haghani/.conda/envs/afprofile/lib/python3.8/site-packages/jax/_src/interpreters/pxla.py", line 1934, in __call__
>     results = self.xla_executable.execute_sharded(input_bufs)
> jax._src.traceback_util.UnfilteredStackTrace: jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 111289565184 bytes.
> BufferAssignment OOM Debugging.
> BufferAssignment stats:
>              parameter allocation:  384.71MiB
>               constant allocation:    48.6KiB
>         maybe_live_out allocation:    1.11TiB
>      preallocated temp allocation:  126.27GiB
>   preallocated temp fragmentation:         0B (0.00%)
>                  total allocation:    1.24TiB
> Peak buffers:
> 	Buffer 1:
> 		Size: 103.65GiB
> 		Operator: op_name="jit(apply_fn)/jit(main)/alphafold/alphafold_iteration/while/body/evoformer/__layer_stack_no_state_1/while/body/dynamic_update_slice" source_file="/home/haghani/.local/lib/python3.8/site-packages/haiku/_src/stateful.py" source_line=640
> 		XLA Label: fusion
> 		Shape: bf16[48,512,8,532,532]
> 		==========================
> 
> 	Buffer 2:
> 		Size: 103.65GiB
> 		Operator: op_name="jit(apply_fn)/jit(main)/alphafold/alphafold_iteration/while/body/evoformer/__layer_stack_no_state_1/while/body/dynamic_update_slice" source_file="/home/haghani/.local/lib/python3.8/site-packages/haiku/_src/stateful.py" source_line=640
> 		XLA Label: fusion
> 		Shape: bf16[48,512,8,532,532]
> 		==========================
> 
> 	Buffer 3:
> 		Size: 99.75GiB
> 		Operator: op_name="jit(apply_fn)/jit(main)/alphafold/alphafold_iteration/while/body/evoformer/__layer_stack_no_state_1/while/body/dynamic_update_slice" source_file="/home/haghani/.local/lib/python3.8/site-packages/haiku/_src/stateful.py" source_line=640
> 		XLA Label: fusion
> 		Shape: bf16[48,532,8,512,512]
> 		==========================
> 
> 	Buffer 4:
> 		Size: 99.75GiB
> 		Operator: op_name="jit(apply_fn)/jit(main)/alphafold/alphafold_iteration/while/body/evoformer/__layer_stack_no_state_1/while/body/dynamic_update_slice" source_file="/home/haghani/.local/lib/python3.8/site-packages/haiku/_src/stateful.py" source_line=640
> 		XLA Label: fusion
> 		Shape: bf16[48,532,8,512,512]
> 		==========================
> 
> 	Buffer 5:
> 		Size: 53.85GiB
> 		Operator: op_name="jit(apply_fn)/jit(main)/alphafold/alphafold_iteration/while/body/evoformer/__layer_stack_no_state_1/while/body/dynamic_update_slice" source_file="/home/haghani/.local/lib/python3.8/site-packages/haiku/_src/stateful.py" source_line=640 deduplicated_name=fusion.717
> 		XLA Label: fusion
> 		Shape: bf16[48,532,4,532,532]
> 		==========================
> 
> 	Buffer 6:
> 		Size: 53.85GiB
> 		Operator: op_name="jit(apply_fn)/jit(main)/alphafold/alphafold_iteration/while/body/evoformer/__layer_stack_no_state_1/while/body/dynamic_update_slice" source_file="/home/haghani/.local/lib/python3.8/site-packages/haiku/_src/stateful.py" source_line=640
> 		XLA Label: fusion
> 		Shape: bf16[48,532,4,532,532]
> 		==========================
> 
> 	Buffer 7:
> 		Size: 53.85GiB
> 		Operator: op_name="jit(apply_fn)/jit(main)/alphafold/alphafold_iteration/while/body/evoformer/__layer_stack_no_state_1/while/body/dynamic_update_slice" source_file="/home/haghani/.local/lib/python3.8/site-packages/haiku/_src/stateful.py" source_line=640 deduplicated_name=fusion.717
> 		XLA Label: fusion
> 		Shape: bf16[48,532,4,532,532]
> 		==========================
> 
> 	Buffer 8:
> 		Size: 53.85GiB
> 		Operator: op_name="jit(apply_fn)/jit(main)/alphafold/alphafold_iteration/while/body/evoformer/__layer_stack_no_state_1/while/body/dynamic_update_slice" source_file="/home/haghani/.local/lib/python3.8/site-packages/haiku/_src/stateful.py" source_line=640
> 		XLA Label: fusion
> 		Shape: bf16[48,532,4,532,532]
> 		==========================
> 
> 	Buffer 9:
> 		Size: 12.47GiB
> 		Operator: op_name="jit(apply_fn)/jit(main)/alphafold/alphafold_iteration/while/body/evoformer/__layer_stack_no_state_1/while/body/dynamic_update_slice" source_file="/home/haghani/.local/lib/python3.8/site-packages/haiku/_src/stateful.py" source_line=640 deduplicated_name=fusion.782
> 		XLA Label: fusion
> 		Shape: f32[48,512,532,256]
> 		==========================
> 
> 	Buffer 10:
> 		Size: 12.47GiB
> 		Operator: op_name="jit(apply_fn)/jit(main)/alphafold/alphafold_iteration/while/body/evoformer/__layer_stack_no_state_1/while/body/dynamic_update_slice" source_file="/home/haghani/.local/lib/python3.8/site-packages/haiku/_src/stateful.py" source_line=640 deduplicated_name=fusion.4980
> 		XLA Label: fusion
> 		Shape: f32[48,512,532,256]
> 		==========================
> 
> 	Buffer 11:
> 		Size: 12.47GiB
> 		Operator: op_name="jit(apply_fn)/jit(main)/alphafold/alphafold_iteration/while/body/evoformer/__layer_stack_no_state_1/while/body/dynamic_update_slice" source_file="/home/haghani/.local/lib/python3.8/site-packages/haiku/_src/stateful.py" source_line=640 deduplicated_name=fusion.5129
> 		XLA Label: fusion
> 		Shape: f32[48,512,532,256]
> 		==========================
> 
> 	Buffer 12:
> 		Size: 12.47GiB
> 		Operator: op_name="jit(apply_fn)/jit(main)/alphafold/alphafold_iteration/while/body/evoformer/__layer_stack_no_state_1/while/body/dynamic_update_slice" source_file="/home/haghani/.local/lib/python3.8/site-packages/haiku/_src/stateful.py" source_line=640 deduplicated_name=fusion.782
> 		XLA Label: fusion
> 		Shape: f32[48,512,532,256]
> 		==========================
> 
> 	Buffer 13:
> 		Size: 12.47GiB
> 		Operator: op_name="jit(apply_fn)/jit(main)/alphafold/alphafold_iteration/while/body/evoformer/__layer_stack_no_state_1/while/body/dynamic_update_slice" source_file="/home/haghani/.local/lib/python3.8/site-packages/haiku/_src/stateful.py" source_line=640 deduplicated_name=fusion.4980
> 		XLA Label: fusion
> 		Shape: f32[48,512,532,256]
> 		==========================
> 
> 	Buffer 14:
> 		Size: 12.47GiB
> 		Operator: op_name="jit(apply_fn)/jit(main)/alphafold/alphafold_iteration/while/body/evoformer/__layer_stack_no_state_1/while/body/dynamic_update_slice" source_file="/home/haghani/.local/lib/python3.8/site-packages/haiku/_src/stateful.py" source_line=640 deduplicated_name=fusion.5129
> 		XLA Label: fusion
> 		Shape: f32[48,512,532,256]
> 		==========================
> 
> 	Buffer 15:
> 		Size: 12.47GiB
> 		Operator: op_name="jit(apply_fn)/jit(main)/alphafold/alphafold_iteration/while/body/evoformer/__layer_stack_no_state_1/while/body/dynamic_update_slice" source_file="/home/haghani/.local/lib/python3.8/site-packages/haiku/_src/stateful.py" source_line=640
> 		XLA Label: fusion
> 		Shape: pred[48,512,532,1024]
> 		==========================
> 
> The stack trace below excludes JAX-internal frames.
> The preceding is the original exception that occurred, unmodified.
> 
> --------------------
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "./run_AFP.py", line 342, in <module>
>     app.run(main)
>   File "/home/haghani/.conda/envs/afprofile/lib/python3.8/site-packages/absl/app.py", line 312, in run
>     _run_main(main, args)
>   File "/home/haghani/.conda/envs/afprofile/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
>     sys.exit(main(argv))
>   File "./run_AFP.py", line 321, in main
>     predict_structure(
>   File "./run_AFP.py", line 252, in predict_structure
>     loss, aux, msa_params, opt_state = update(msa_params, opt_state, processed_feature_dict)
>   File "./run_AFP.py", line 231, in update
>     (loss, aux), grads = jax.value_and_grad(loss_fn, has_aux=True)(msa_params, processed_feature_dict)
>   File "./run_AFP.py", line 223, in loss_fn
>     prediction_result = model_runner.predict(msa_params, processed_feature_dict) #The params for model runner are contained within self
>   File "/projects/protein-structure-prediction/AFProfile/src/alphafold/model/model.py", line 170, in predict
>     result = self.apply(self.params, jax.random.PRNGKey(0), feat)
> jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 111289565184 bytes.

I also have tried running the code on multiple GPUs but it did not help, as well. I appreciate your assistance in this regard.

**Comment by tkramer-motion** [comment]
I was able to run after setting the env variables described here: https://jax.readthedocs.io/en/latest/gpu_memory_allocation.html. I think I set XLA_PYTHON_CLIENT_MEM_FRACTION to 1

**Comment by Maryam-Haghani** [comment]
Thanks @tkramer-motion,
I could manage running the code.
