### ISSUE TITLE
Coloring output pdb files by pLDDT

### ISSUE THREAD

**Issue by Franz4272** [patrickbryant1/AFProfile#4]
Hi Patrick,

I hope you are doing well. I can color the pdb files by b-factors in PyMOL, but when I run a script to color by pLDDT the heterodimer is a solid color and does not match the b-factors. I have attached two screen shots showing this. I tried using the following two scripts: [coloraf.py](https://github.com/cbalbin-bio/pymol-color-alphafold) and [colour_af_plddt.py](https://github.com/BobSchiffrin/pymol_scripts). I am not sure why this is happening. Please let me know your thoughts when you get the chance. 

Thank you,
Franz 
![unrelaxed_136 b-factors](https://github.com/patrickbryant1/AFProfile/assets/100600329/4d7f06c7-d582-4421-93db-716383c1eb22) 
![unrelaxed_136 pLDDT scripts](https://github.com/patrickbryant1/AFProfile/assets/100600329/e8f2b143-883b-414a-a838-7df6284a62be)

**Comment by patrickbryant1** [comment]
Hi,

I do not know what the scripts you linked do. Perhaps there is a scaling issue (the plDDT is in range 0-1 now)?. The plDDT is written to the B-factor column (which is why the pymol colouring works). Please contact the authors of the other scripts for these errors.

Best,

Patrick

**Comment by Franz4272** [comment]
Hi Patrick,

I changed the pLDDT range from 0-100 to 0-1 as you suggested and it works perfectly. Thank you so much!

Best,
Franz
