### ISSUE TITLE
Trouble running heterotrimer

### ISSUE THREAD

**Issue by Franz4272** [patrickbryant1/AFProfile#5]
Hi Patrick,

I hope you had a nice weekend. I have gotten a lot of very nice heterodimer structures using AFProfile, but I am unable to run heterotrimers. I am not sure if this has to do with the way AFProfile was installed on my university's computer. I have attached a text file containing the errors from trying to run a heterotrimer. Please let me know your  thoughts when you get the chance. 

Thank you,
Franz 

[log.txt](https://github.com/patrickbryant1/AFProfile/files/12568535/log.txt)

**Comment by patrickbryant1** [comment]
Hi Franz,
Nice that you managed to run it, great work!

You are out of memory. This is stated in the error message: : jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 12531662848

Using gradient descent to improve the predictions take more memory than running a single pass, which means that you can't fit the biggest structures. You can try to get a bigger GPU with 80 Gb RAM or run all possible pairs of chains in your trimer and then superimpose the resulting parts to get the full trimer. This is essentially what we do here, but you can do it manually: https://www.nature.com/articles/s41467-022-33729-4

Hope this helps!

Patrick

**Comment by Franz4272** [comment]
Hi Patrick,

Thank you for your quick and helpful response. Did you mean at least 80 more Gb RAM, or at least 80 Gb RAM total? I am currently running AFProfile on a GPU with 512 Gb RAM. 

If I cannot get more RAM I will try to superimpose the heterodimer structures as you suggested. 

Thank you!
Franz

**Comment by patrickbryant1** [comment]
Hi,

I mean in total. I do not see how you can have such a large GPU. Perhaps this is the RAM of the node? If you can invoke shared memory btw all cores on the node you can perhaps use this amount, but you should not be out of memory then which is why I think you do not use this amount. 

Try asking the maintainers of your GPUs how to specify the RAM for each run. If you have 512 Gb, you should be able to run any structure.

**Comment by Franz4272** [comment]
Hi Patrick,

I misunderstood the specifications of our GPU. Our GPU only has 48 Gb RAM for each run. We are in the process of getting access to a GPU with 80 Gb RAM. I apologize for the confusion.

Thank you for your help! 

Best,
Franz
