### ISSUE TITLE
AFProfile for monomers?

### ISSUE THREAD

**Issue by Franz4272** [patrickbryant1/AFProfile#6]
Hi Patrick,

I hope you are doing well. Is it possible to use AFProfile to predict the structures of monomers with greater accuracy than other existing methods due to gradient descent? Can I run AFProfile with only one sequence? Please let me know when you get the chance.  

Thank you, 
Franz

**Comment by patrickbryant1** [comment]
Hi Franz,

Yes, this is possible and has been done before using AF-multimer with better results in some cases.

I have not tested this with AFProfile, but the principle is the same.

**Comment by Franz4272** [comment]
Hi Patrick,

Thank you so much for letting me know. I hope you have a nice weekend.

Best,
Franz
