### ISSUE TITLE
Out of Memory

### ISSUE THREAD

**Issue by johnny-rodriguez** [patrickbryant1/AFProfile#8]
I ran the example and ran into the following error:

jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 4770354232 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  372.76MiB
              constant allocation:    48.5KiB
        maybe_live_out allocation:    9.64GiB
     preallocated temp allocation:    4.44GiB
                 total allocation:   14.44GiB
              total fragmentation:  680.30MiB (4.60%)

I am running a 3080 ti GPU. 
Does this only run on a more powerful GPU? Or is something else wrong?

**Comment by patrickbryant1** [comment]
Hi, yes you probably need a more powerful GPU.
